# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flutter_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'YYText', '1.0.7'
  # Pods for Flutter_iOS

  target 'Flutter_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flutter_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

    ## ==============Flutter ==============
    ##绝对路径

    flutter_application_path = '../flutter_library/'
    # load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

    eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
    ## ==============Flutter ==============

